### ISSUE TITLE
Custom content types must also filter on the user's feed

### ISSUE THREAD

**Issue by benwerd** [idno/Known#178]
##

**Comment by mapkyca** [comment]
Fixed, surely?

**Comment by kylewm** [comment]
@benwerd can you tell us what this issue is for? Looking at the history, it looks to me like you added configurable ContentType filtering the day *before* filing this issue, so it must describe something other than what I assumed :P

**Comment by benwerd** [comment]
This is actually not fixed, and _is_ something I'd like to work on.

You can filter the main feed by content type. You can't, however, visit a user's profile on a multi-user site and filter _that_ feed by content type. That would be a useful thing to do, eg to find all the photos a particular user had uploaded.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/178" class="u-in-reply-to"></a>Gotcha.

That's just a UI thing though, primarily.

Perhaps a content bar (like the posting one) as part of the profile header - user's photos, posts, etc etc, depending what plugins are active.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/178" class="u-in-reply-to"></a>For that matter, there is a content context menu on the dropdown... seems natural (to me) that this becomes context sensitive to the page.

**Comment by mapkyca** [comment]
Related #1587

**Comment by johanbove** [comment]
> 
> 
> For that matter, there is a content context menu on the dropdown... seems natural (to me) that this becomes context sensitive to the page.

Since the URL content-type filter on the /profile page already works, this is indeed a matter of making the code which generates the list of links in the toolbar to have a dynamic "root" url. See the file templates>default>shell>toolbar>content>type.tpl.php where `getDisplayURL()` is called with the `content/` path hard-coded. Solution to resolve this issue would be to make the `content/` path within "type.tpl.php" be aware of the active context; either "/content" or "/profile".
