### ISSUE TITLE
Known says that mod rewrite is disabled when it actually isn't.

### ISSUE THREAD

**Issue by hopesthoughts** [idno/known#2509]
When trying to install known on a Hostgator shared plan, it gave this error. Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to known.min.js

You can usually fix this by setting AllowOverride All in your Apache configuration.
    I actually had to contact Hostgator support to help fix this issue, here's what they did. "This was an incorrect assumption made by the CMS during the installation process. To check this configuration setting, the server sends a request for a non-existent file that redirects to a different file on the server. The redirect that the CMS is testing is defined in the .htaccess file, and anything other than an "OK" response from the server will cause the test to fail and return an error. The issue in this scenario was not due to server configuration, but instead the .htaccess file did not include the specific redirect the CMS was testing. I was able to append the default .htaccess for Known CMS to the .htaccess file in your domain's document root, and the error went away, allowing the installation to complete as normal."

**Comment by mapkyca** [comment]
Thanks for the feedback. This was a known problem a little while back, but should have been resolved in recent builds.

**Comment by hopesthoughts** [comment]
I'm not exactly sure how to do the Github install thing, so I just downloaded one of the zip archives, and installed it that way. Is there a more recent one of those? Although I'm pretty sure it said 7/21/2019 on it.

**Comment by geekaroni** [comment]
Still an issue btw. Tried installing this on two different servers and both telling me "

Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to known.min.js

You can usually fix this by setting AllowOverride All in your Apache configuration.
"
Which is not true. I've restarted the server and all needed services and still no avail.

**Comment by rschr** [comment]
Same here (Ubuntu 16.04 Server, Apache 2.4, PHP 7.2). The access.log shows this, before the page containing the message is loaded:

`192.168.1.8 - - [05/Jan/2020:16:23:41 +0100] "GET ///js/canary.js HTTP/1.1" 404 5652 "-" "-"`

**Comment by mapkyca** [comment]
Looks an awful lot like your site hostname is not being detected - but that's just a first look

**Comment by Kaidok5797** [comment]
I'm having this issue too. How can I fix this?

**Comment by mambax7** [comment]
+1
same issue here

**Comment by mambax7** [comment]
OK, the answer was in another closed issue: https://github.com/idno/known/issues/2725, with this answer from csjjpm:

> The known-1.0.0.zip I downloaded (28MB) was missing a lot of files. I grabbed a known-master.zip from github (2MB) and copied it over. Now everything is working.
