### ISSUE TITLE
Sub URL site

### ISSUE THREAD

**Issue by scottix** [idno/Known#521]
I am not sure if this is addressed. I am having problems using a sub-url for an install I want to setup with.

So I want https://server/known/

Let me know how I can do this with all the urls working correctly.

**Comment by trilliums** [comment]
Could you outline what the blockers are to getting Known installed in subdirectories?

**Comment by physcocode** [comment]
@trilliums the block is in the way toro routes the URL we have to explicitly include the subdirectory part /known etc to the routes.
A way out would be detecting whether the installation is on a sub directory and use a variable to store directory name then route using directory e.g.. $subdir/homepage would be URL for homepage etc

**Comment by physcocode** [comment]
adding following lines of code to toro and using Torosub::serve instead of Toro:serve solves the problem for me ! This is not 100% garentee to work  when toro receive the post method cause it has not been tested to handle post request yet !

class Torosub {
	public static function serve($handlers) {
		/*
		 * Toro prefers the $_SERVER["PATH_INFO"] var to get the requested URL.
		 * If this var is present, everything seems to be correct.
		 * If it is not, some weird errors occur.
		 * For example, Toro sometimes can not route to the index route ("/"), when the app is not running from the servers document root.
		 * By constructing PATH_INFO manually using REQUEST_URI and SCRIPT_NAME, we can work around this problem.
		 */
		if(!isset($_SERVER["PATH_INFO"])) {
			$r = $_SERVER['REQUEST_URI'];
			if(strpos($r, '?')) {
				$r = strstr($r, '?', true);
			}

			$request = explode('/', $r);
			$script = explode('/', $_SERVER['SCRIPT_NAME']);

			for($i = 0; $i < count($script); $i++) {
				if($request[$i] !== $script[$i]) {
					break;
				}
			}
			
			$u = array_slice($request, $i);

			if($u[count($u)-1] === '') {
				$u = array_slice($u, 0, count($u)-1);
			}
			
			$_SERVER["PATH_INFO"] = '/'.implode('/', $u);
		}
		
		\Toro::serve($handlers);
	}
}

**Comment by physcocode** [comment]
@benwerd : Another workaround for this is to create a ToroHook for before_request which modifies the value of $_SERVER['PATH_INFO'] stripping out a defined base directory. You can also just extend ToroWeb and wrap the serve() function with the path info changes. what about this ?

**Comment by benwerd** [comment]
Hi gang - please test with the latest. A bunch of code to deal with this was committed yesterday.

**Comment by danito** [comment]
doesn't work for me : 
 Fatal error:  Call to a member function log() on null in /var/www/virtual/nxd4n/nixis.me/Known/Idno/Data/MySQL.php on line 805
[Mon Jul 06 22:58:37 2015] [warn] [client 128.79.104.110] mod_fcgid: stderr: PHP Fatal error:  Call to a member function log() on null in /var/www/virtual/nxd4n/nixis.me/Known/Idno/start.php on line 27

And after warmup, DB is empty (tables are there, but no default settings but version). Login/register is not possible.

**Comment by benwerd** [comment]
I've just pushed some new changes, and installed from scratch in a subdirectory.

@danito - It's possible that our rewrite rules are incompatible with fcgi_bin, which your host seems to be running. I'll do some more testing.

**Comment by danito** [comment]
Pulled and testing.
FYI after deleting config.ini and hitting F5 from https://nixis.me/Known/login I got a loop:
https://nixis.me/Known/session/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/warmup/

Entering https://nixis.me/Known was ok.

**Comment by danito** [comment]
Still the same.
I have this in my root nixis.me/.htaccess : 
```xml
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS
```
I don't know if this interferes with the Know rewriting..

**Comment by benwerd** [comment]
It does. In particular the RewriteBase will. Check out the changed version
in the latest Known .htaccess.

On Fri, Jul 10, 2015 at 1:57 AM, Daniel nix <notifications@github.com>
wrote:

> Still the same.
> I have this in my root nixis.me/.htaccess :
>
> # BEGIN YOURLS
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteBase /
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule ^.*$ /yourls-loader.php [L]
> </IfModule>
> # END YOURLS
>
> I don't know if this interferes with the Know rewriting..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/521#issuecomment-120305398>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
