### ISSUE TITLE
Hashtags not workin

### ISSUE THREAD

**Issue by tsparks** [idno/Known#890]
I upgraded my self hosted site to 7.1.1 from 6.3 and ever sense the #hashtags  no longer return content; the hashtag shows on the post as a link but I click   it ,  it doesn't return any linked posts.

My site: http://tom.sparkshouse.com

Any advice would appreciated.... Thanks

**Comment by kylewm** [comment]
note: we noticed when looking at this problem in IRC that the old style content/all?q=#hashtag links still work, but the new /tag/hashtag links are empty.

**Comment by kylewm** [comment]
@tsparks have you tried upgrading to the latest version (0.7.8)?

0.7.1 is several months old at this point, and it's very possible this problem was already fixed.

**Comment by tsparks** [comment]
I will try that

**Comment by tsparks** [comment]
I upgraded my version to 7.8, and the hashtag issue still exisits.  During the upgrade I think I found a useful clue, my site is not setup in the standard default way. All the uploaded files (.jpg's) are in a folder called data. The config file points there

uploadpath = "/usr/home/tomsparks/public_html/tom/data/"

I believe it is suppose to point to Uploads. Can I rewrite the conf file to point to Uploads and move the content from data to uploads?  I am not sure if the program will break if I do that.

**Comment by kylewm** [comment]
Hmm, I'd be surprised if this particular issue was affected by the Uploads folder.

Could you provide some details of your setup. Are you using MySQL or MongoDB? Apache or nginx? What hosting provider? Is there anything interesting in the server logs right after you try to hit a tag URL like http://tom.sparkshouse.com/tag/photography?

**Comment by tsparks** [comment]
Site is hosted by Pair.net
FreeBSD
MySQL
Appche
PHP 5.3.5. 

I don't think I have access to server logs I will look into that,  I run this out of a sub directory as a sub domain as you see by the URL

**Comment by kylewm** [comment]
> PHP 5.3.5. 

That might be the problem right there. Known requires 5.4 or above (https://github.com/idno/Known/blob/master/docs/install/requirements.md)

**Comment by davidmead** [comment]
One thing that could be a related issue is my hashtags, coming in from Instagram, are breaking if the start with a number

![screen shot 2015-05-12 at 2 55 08 pm](https://cloud.githubusercontent.com/assets/1266930/7597040/f5bfa5f0-f8b6-11e4-8b73-17a030fdb5fe.png)

Only started happening recently. I thought I'd inadvertently put a space between the two, but when I edit the Known post I still get the same thing.

**Comment by kylewm** [comment]
@davidmead that looks like a separate issue, since http://blog.davidjohnmead.com/tag/365daysofme still works for your site even though hashtags containing numbers are not auto-linked. If want to file an issue, refer to this line of the code 
https://github.com/idno/Known/blob/0e865a83ae9c144344402d0050a9b47ed5598bb1/Idno/Core/Template.php#L271

In particular the regex matches `\p{L}` which is letters only, no numbers.

**Comment by benwerd** [comment]
We're going to push a fix for this imminently. The regex is indeed broken.

**Comment by tsparks** [comment]
I was mistaken I have php54.cgi running in my web folder

I recreated my site using a fresh install of Known 7.8,  I kept three things, the htaccess file, the config.ini and the data folder.

One of those three things is the problem. I never changed the config,ini settings so it has to be the folder I upload to or the htaccess file. I think it  is the data folder.

**Comment by benwerd** [comment]
Various fixes for hashtags have now been committed.

**Comment by benwerd** [comment]
Confirming that an upgrade will fix the problem. A new installer will be rolled out on Saturday morning PDT.
